PROG_VERSION=0.9.9
PROG_BUILDTIME=1465331943
UPDATER_VERSION=1

DEFINES += PROG_VERSION=\\\"$$PROG_VERSION\\\" PROG_BUILDTIME=\\\"$$PROG_BUILDTIME\\\" UPDATER_VERSION=\\\"$$UPDATER_VERSION\\\"
VERSION=$$PROG_VERSION

DEFINES += LOG_LIMIT=1000000

win32 {
    DEFINES += TASK_NAME=\\\"UPSTUpdater\\\"
}

# Remove this on production builds
DEFINES += TESTING_MODE
