PROG_VERSION=0.9.8
PROG_BUILDTIME=1464266529
UPDATER_VERSION=1

DEFINES += PROG_VERSION=\\\"$$PROG_VERSION\\\" PROG_BUILDTIME=\\\"$$PROG_BUILDTIME\\\" UPDATER_VERSION=\\\"$$UPDATER_VERSION\\\"
VERSION=$$PROG_VERSION

DEFINES += LOG_LIMIT=1000000

# Remove this on production builds
DEFINES += TESTING_MODE
