; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "UPST"
#define MyAppVersion "0.9.9"
#define MyAppPublisher "Ultimobile"
#define MyAppURL "http://ultimobile.com/"
#define MyAppExeName "UPST.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BE25B3DA-BA87-45CE-A107-B36FFFAC1C02}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\Ultimobile/UPST
DisableProgramGroupPage=yes
OutputDir=C:\Users\Homer\Documents\Qt\UPST\installer
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Types]
Name: "main"; Description: "Regular"
Name: "laptop"; Description: "UPST Laptop"

[Components]
Name: "main"; Description: "Main Files"; Types: main laptop; Flags: fixed
Name: "laptop"; Description: "UPST Laptop"; Types: laptop

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Homer\Documents\Qt\UPST\release\UPST.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Homer\Documents\Qt\UPST\release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurrentStep: TSetupStep);
  var exe : String;
  var ErrorCode : Integer;
begin
  if not IsComponentSelected('laptop') then begin
    exit;
  end;

  if (CurrentStep = ssPostInstall) then begin
    ShellExecAsOriginalUser('', 'UPST.exe', 'taskcreate Administrator ChoiceRDPAdmin', ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ErrorCode);
    if ErrorCode <> 0 then begin
        MsgBox('Could not create task ' + IntToStr(ErrorCode), mbError, MB_OK);
    end;
  end;
end;
